---
- name: Install Java 8 
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
   - unzip
   - java-1.8.0-openjdk
   - libselinux-python
   - libsemanage-python
  sudo: yes

- name: Download GoCD repo
  get_url: 
    url: https://download.gocd.org/gocd.repo 
    dest: /etc/yum.repos.d/gocd.repo
  sudo: yes

- name: Install GoCD
  yum: 
    name: go-server
    state: present
  sudo: yes

- name: Start GoCD
  service: name=go-server state=started enabled=yes
  sudo: yes

