---
- name: Check if pipeline config repos already present
  lineinfile:
    path: /etc/go/cruise-config.xml
    line: "  <config-repos>"
    state: present
  check_mode: yes
  register: config_repos

- name: If not, add example pipeline to GoCD
  lineinfile:
    dest: /etc/go/cruise-config.xml
    insertbefore: '<agents>'
    line: '<config-repos> 
           <config-repo pluginId="json.config.plugin" id="gocd-demo-config-repo-json"> 
           <git url="https://github.com/arvindsv/gocd-demo-config-repo-json.git" /> 
           </config-repo>
           </config-repos>'
    state: present
  when: (config_repos is changed)

- name: Wait for example pipeline to be ready
  shell: "curl -D - --silent --max-time 5 http://localhost:8153/go/admin/pipeline_group/demo/edit"
  register: result
  until: (result.stdout.find("200 OK") != -1)
  retries: 20
  delay: 5
  changed_when: false
  check_mode: no
