---
- name: Install Java 8
  include_role:
    name: gocd-server
    tasks_from: java-8

- name: Install git
  include_role:
    name: gocd-server
    tasks_from: git

- name: Download GoCD repo
  get_url: 
    url: https://download.gocd.org/gocd.repo 
    dest: /etc/yum.repos.d/gocd.repo

- name: Install GoCD agent
  yum: 
    name: go-agent
    state: present

- name: Start GoCD agent
  service: name=go-agent state=started enabled=yes

- name: Wait for agent to register with server
  lineinfile:
    path: /etc/go/cruise-config.xml
    line: "  <agents>"
    state: present
  check_mode: yes
  register: content
  until: (content is not changed)
  retries: 20
  delay: 5
