---
- name: Install Java 8 
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
   - unzip
   - java-1.8.0-openjdk
   - libselinux-python
   - libsemanage-python

- name: Install git
  yum: 
    name: git
    state: present

- name: Download GoCD repo
  get_url: 
    url: https://download.gocd.org/gocd.repo 
    dest: /etc/yum.repos.d/gocd.repo

- name: Install GoCD agent
  yum: 
    name: go-agent
    state: present

- name: Start GoCD agent
  service: name=go-agent state=started enabled=yes


