---
- name: Install Jenkins plugins
  jenkins_plugin:
    name: "{{ item }}"
  with_items: 
    - git:latest
  notify: restart jenkins
    
- name: Install plugins
  jenkins_plugin:
    name: "{{ item }}"
  with_items: 
    - git:latest
  sudo: yes

