---
- name: Install Java 8 
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
   - unzip
   - java-1.8.0-openjdk
   - libselinux-python
   - libsemanage-python

- name: Install git
  yum: 
    name: git
    state: present

- name: Download GoCD repo
  get_url: 
    url: https://download.gocd.org/gocd.repo 
    dest: /etc/yum.repos.d/gocd.repo

- name: Create directory for GoCD server 
  file:
    path: /var/go
    state: directory
    mode: 0755

- name: Install GoCD server
  yum: 
    name: go-server
    state: present

- name: Start GoCD server
  service: name=go-server state=started enabled=yes

- name: Wait for GoCD to start up 
  shell: "curl -D - --silent --max-time 5 http://localhost:8153/go/"
  register: result
  until: (result.stdout.find("302 Found") != -1)
  retries: 20
  delay: 5
  changed_when: false
  check_mode: no
